version: '2'

networks:
  phoenix-net:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - phoenix-net
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=discuss_dev
    ports:
      - '5439:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'